#!/bin/sh

CACHE_DIR="$HOME/.cache/pacmerge/"

mkcdir() {
	if [[ $# -eq 1 ]]; then
		mkdir -p "$1" && cd "$1"
	fi
}

[ -e "$CACHE_DIR" ] && cd ~/.cache/pacmerge || mkcdir "$CACHE_DIR"
asp checkout $1
cd $1/repos/*
makepkg -si
